aerospike:
    connection_timeout: 100
    read_timeout: 1
    connection_queue_size: 512
    write_timeout: 10
    hosts:
        -
            host: aero-base.bali
            port: 3000

http:
    port: 8080

memcache:
    port: 11212
